name: Olivia Sabik
markdown: kramdown

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : sabik site
author :
  name : Olivia Sabik
  email : olivia.sabik@gmail.com
  github : oliviasabik
  twitter : oliviasabik

plugins:
  - jekyll-sitemap

production_url : http://oliviasabik.github.io/
BASE_PATH : http://oliviaabik.github.io/

theme: jekyll-theme-cayman